const Users = [
  {
    id: 1,
    first_name: "Randa",
    last_name: "Befroy",
    email: "rbefroy0@techcrunch.com",
    gender: "Bigender",
    age: 1,
  },
  {
    id: 2,
    first_name: "Jamey",
    last_name: "Blockey",
    email: "jblockey1@wikispaces.com",
    gender: "Male",
    age: 2,
  },
  {
    id: 3,
    first_name: "Oswell",
    last_name: "Bibby",
    email: "obibby2@lycos.com",
    gender: "Male",
    age: 3,
  },
  {
    id: 4,
    first_name: "Rudyard",
    last_name: "Fiddler",
    email: "rfiddler3@slashdot.org",
    gender: "Male",
    age: 4,
  },
  {
    id: 5,
    first_name: "Carola",
    last_name: "Siggins",
    email: "csiggins4@surveymonkey.com",
    gender: "Female",
    age: 5,
  },
  {
    id: 6,
    first_name: "Barn",
    last_name: "Ruselin",
    email: "bruselin5@lulu.com",
    gender: "Male",
    age: 6,
  },
  {
    id: 7,
    first_name: "Angelia",
    last_name: "Rotherham",
    email: "arotherham6@qq.com",
    gender: "Female",
    age: 7,
  },
  {
    id: 8,
    first_name: "Petronella",
    last_name: "De Beauchamp",
    email: "pdebeauchamp7@dion.ne.jp",
    gender: "Female",
    age: 8,
  },
  {
    id: 9,
    first_name: "Ward",
    last_name: "Corish",
    email: "wcorish8@shutterfly.com",
    gender: "Male",
    age: 9,
  },
  {
    id: 10,
    first_name: "Ringo",
    last_name: "Fallanche",
    email: "rfallanche9@slashdot.org",
    gender: "Male",
    age: 10,
  },
  {
    id: 1,
    first_name: "Kelly",
    last_name: "Tomczykiewicz",
    email: "ktomczykiewicz0@istockphoto.com",
    gender: "Female",
    age: 1,
  },
  {
    id: 2,
    first_name: "Bent",
    last_name: "Thaw",
    email: "bthaw1@nps.gov",
    gender: "Male",
    age: 2,
  },
  {
    id: 3,
    first_name: "Mame",
    last_name: "Giovanardi",
    email: "mgiovanardi2@about.com",
    gender: "Female",
    age: 3,
  },
  {
    id: 4,
    first_name: "Pen",
    last_name: "Firebrace",
    email: "pfirebrace3@vkontakte.ru",
    gender: "Polygender",
    age: 4,
  },
  {
    id: 5,
    first_name: "Brena",
    last_name: "Ranshaw",
    email: "branshaw4@slashdot.org",
    gender: "Female",
    age: 5,
  },
  {
    id: 6,
    first_name: "Abbot",
    last_name: "Mardee",
    email: "amardee5@technorati.com",
    gender: "Male",
    age: 6,
  },
  {
    id: 7,
    first_name: "Beatrix",
    last_name: "Lamy",
    email: "blamy6@walmart.com",
    gender: "Female",
    age: 7,
  },
  {
    id: 8,
    first_name: "Olivette",
    last_name: "Lochet",
    email: "olochet7@ibm.com",
    gender: "Female",
    age: 8,
  },
  {
    id: 9,
    first_name: "Julina",
    last_name: "O'Flynn",
    email: "joflynn8@auda.org.au",
    gender: "Female",
    age: 9,
  },
  {
    id: 10,
    first_name: "Huntington",
    last_name: "Harbidge",
    email: "hharbidge9@accuweather.com",
    gender: "Male",
    age: 10,
  },
  {
    id: 11,
    first_name: "Jacques",
    last_name: "Waplington",
    email: "jwaplingtona@livejournal.com",
    gender: "Male",
    age: 11,
  },
  {
    id: 12,
    first_name: "Aila",
    last_name: "Kroon",
    email: "akroonb@shop-pro.jp",
    gender: "Female",
    age: 12,
  },
  {
    id: 13,
    first_name: "Jessi",
    last_name: "Vala",
    email: "jvalac@dmoz.org",
    gender: "Female",
    age: 13,
  },
  {
    id: 14,
    first_name: "Barnabe",
    last_name: "Gittus",
    email: "bgittusd@squarespace.com",
    gender: "Male",
    age: 14,
  },
  {
    id: 15,
    first_name: "Penny",
    last_name: "Bartul",
    email: "pbartule@cmu.edu",
    gender: "Female",
    age: 15,
  },
]

export default Users
